### ISSUE TITLE
Types missing?

### ISSUE THREAD

**Issue by AleksanderBondar** [rhysd/remark-emoji#22]
At the moment there are no types after installation.
Possible solutions: Move index.d.ts from types folder to root folder.

**Comment by rhysd** [comment]
I confirmed index.d.ts was contained correctly.

```console
$ tree node_modules/remark-emoji/
node_modules/remark-emoji/
├── LICENSE
├── README.md
├── index.js
├── package.json
└── types
    └── index.d.ts

1 directory, 5 files
```

Path of index.d.ts is set here.

https://github.com/rhysd/remark-emoji/blob/e073a8f2250500499c8c6ee899cef11a1f6551a7/package.json#L29

I didn't see any issue.
