### ISSUE TITLE
Type hints seem to be incorrect

### ISSUE THREAD

**Issue by kamoshi** [rhysd/remark-emoji#29]
When trying to use this plugin in Astro 3.4 I see the following TypeScript error:

```
Diagnostics:
1. Type 'Plugin<[(RemarkEmojiOptions | undefined)?]>' is not assignable to type 'string | [string, any] | RemarkPlugin<any[]> | [RemarkPlugin<any[]>, any]'.
     Type 'Plugin<[(RemarkEmojiOptions | undefined)?]>' is not assignable to type 'RemarkPlugin<any[]>'.
       The 'this' types of each signature are incompatible.
         Type 'Processor<void, void, void, void>' is missing the following properties from type 'Processor<undefined, undefined, undefined, undefined, undefined>': compiler, freezeIndex, frozen, namespace, and 3 more. [2322]
```

Astro expects an array of the following type:
https://github.com/withastro/astro/blob/5fed432b0c3c84542a3d1b2952d183e9cbe3fa0e/packages/markdown/remark/src/types.ts#L28

This plugin does work correct however.

**Comment by rhysd** [comment]
At least please provide remark packages versions, TypeScript version, your tsconfig.

remark bumped major version last month. It may affect on type definitions.

**Comment by kamoshi** [comment]
Sure

- tsserver: 4.0.0
- TypeScript: 5.2

I use `astro` 3.4, which in turn depends on:
- "unified": "^10.1.2"
- "@types/mdast": "^3.0.12"

The full `package.json` can be seen [here](https://github.com/withastro/astro/blob/5fed432b0c3c84542a3d1b2952d183e9cbe3fa0e/packages/markdown/remark/package.json)

The type expected by Astro is:
```ts
export type RemarkPlugin<PluginParameters extends any[] = any[]> = unified.Plugin<
	PluginParameters,
	mdast.Root
>;

export type RemarkPlugins = (string | [string, any] | RemarkPlugin | [RemarkPlugin, any])[];
```

Problem occurs when passing `remarkEmoji` into an array which has the type `RemarkPlugins`:
![image](https://github.com/rhysd/remark-emoji/assets/18511281/e5d7f400-92bc-44c7-be45-9db76fdaeae4)

**Comment by rhysd** [comment]
Could you share the exact version of remark-emoji package in your local?

If okay, it is helpful to dump all the dependendcies by `npm list --all` and paste it here.

**Comment by kamoshi** [comment]
remark-emoji 4.0.0

Here is the output of `pnpm ls --depth Infinity`:
[out.txt](https://github.com/rhysd/remark-emoji/files/13196534/out.txt)

**Comment by rhysd** [comment]
I improved type definitions in this package and released v4.0.1. Could you try the latest version?

https://github.com/rhysd/remark-emoji/releases/tag/v4.0.1

**Comment by goingtogogo** [comment]
hey hey @rhysd! 
I'm sorry for the lack of details. dependabot brought a PR, and it appears that it started working but not completely😔

(using `remark-emoji` with `next-mdx-remote, @mdx-js`)

<img width="1229" alt="Снимок экрана 2023-11-01 в 09 31 34" src="https://github.com/rhysd/remark-emoji/assets/17799611/a5fe9799-29e5-4b5f-8df1-9412af76331a">

**Comment by kamoshi** [comment]
I still have the same problem:
![image](https://github.com/rhysd/remark-emoji/assets/18511281/327a9bbe-ae95-4b36-a474-bcb506f553aa)

I checked one of the official plugins how they are using types, and it turns out that there might be some problem with TypeScript and remark types in general. This seems relevant:
https://github.com/remarkjs/remark-math/blob/main/packages/remark-math/lib/index.js#L26-L30

Maybe @wooorm would know more?

**Comment by wooorm** [comment]
The types are fine. The problem is that there are different types (because mismatched dependencies). And that’s how TypeScript works: adding one field in a type somewhere is breaking. Which is why I did breaking changes everywhere.

The solution is to update *all* your tools, not just some.
So update MDX too.
And if `next-mdx-remote` is not yet updated, raise a PR to use MDX 3 there.

This is how TS works, it warns when things might not work. You can add a `@ts-expect-error` when you know it works. And otherwise update all your dependencies.

---

> This seems relevant:

Nope, that’s a solution to a bug with how TS generates `.d.ts` files; unrelated to this!

**Comment by wooorm** [comment]
Reading through the types in `remark-emoji`: they look perfect!

**Comment by kamoshi** [comment]
It seems the problem isn't here then, nevertheless thanks and sorry for bugging you :sweat_smile:

**Comment by rhysd** [comment]
I missed this conversation since this issue was closed.

@wooorm Thank you for your follow up.

**Comment by tdkn** [comment]
@rhysd 
First of all, thanks for this useful plugin.

I'm using ﻿remark-emoji with ﻿[contentlayer](https://github.com/contentlayerdev/contentlayer).
After updating from version 4.0.0 to 4.0.1, I've encountered the following error:

```
Type 'Plugin<[(RemarkEmojiOptions | null | undefined)?], Root>' is not assignable to type 'Pluggable<any[]>'.
  Type 'Plugin<[(RemarkEmojiOptions | null | undefined)?], Root>' is not assignable to type 'Plugin<any[], any, any>'.
    The 'this' types of each signature are incompatible.
      Type 'Processor<void, any, void, void> | Processor<void, any, any, any> | Processor<any, any, void, void> | Processor<void, void, void, void>' is not assignable to type 'Processor<undefined, undefined, undefined, undefined, undefined>'.
        Type 'Processor<void, any, void, void>' is missing the following properties from type 'Processor<undefined, undefined, undefined, undefined, undefined>': compiler, freezeIndex, frozen, namespace, and 3 more.
```

> reproduction: https://github.com/tdkn/blog/pull/447

I would appreciate any advice on how to resolve this issue.

**Comment by wooorm** [comment]
`contentlayer` should update things

**Comment by tdkn** [comment]
@wooorm 
Thank you for the quick response.
I will try to investigate where to fix in contentlayer.

P.S.
Contentlayer is not currently being actively maintained and I am not sure if my pull request will be accepted, so I am planning to change to [mdx-bundler](https://github.com/kentcdodds/mdx-bundler) or [@next/mdx](https://nextjs.org/docs/pages/building-your-application/configuring/mdx#nextmdx).
