### ISSUE TITLE
Missing source maps in v5.0.0

### ISSUE THREAD

**Issue by short-dsb** [rhysd/remark-emoji#34]
The following warnings appear when building or running an app that uses `remark-emoji` v5.0.0:

```bash
WARNING in ./node_modules/remark-emoji/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/remark-emoji/index.js.map' file: Error: ENOENT: no such file or directory, open './node_modules/remark-emoji/index.js.map'
```

**Comment by rhysd** [comment]
Yeah, I haven't added `index.js.map` to `files` in package.json when migrating to TypeScript. I should do it.

**Comment by rhysd** [comment]
v5.0.1 fixed this issue. Please upgrade your local dependency.

https://www.npmjs.com/package/remark-emoji/v/5.0.1
