### ISSUE TITLE
Not all node-emoji short codes work

### ISSUE THREAD

**Issue by NathanielHill** [rhysd/remark-emoji#6]
Looks like this is using a 2+ year old version of node-emoji, and hence some common short codes don't work. Would it be possible to upgrade to 1.8.1 and also make a link in the README to currently supported short codes?

I can put together a PR if wanted.

**Comment by rhysd** [comment]
I published 2.0.2. Does it work for you?

**Comment by NathanielHill** [comment]
Awesome, thanks
